#! /bin/bash
# cleandns is free software: you can redistribute it and/or modify
# Copyright (C) 2014  Push Chen

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# You can connect me by email: littlepush@gmail.com, 
# or @me on twitter: @littlepush


#### This file is going to generate the document header file ####

DocHeaderFile=./inc/doc_header_auto_generate.h

> ${DocHeaderFile}

echo "#pragma once" > ${DocHeaderFile}

for doc in $(ls ./doc); do
    def_name=CLEANDNS_DOC_$(echo ${doc} | awk '{print toupper($0)}')
    echo "#define ${def_name} \"$(base64 doc/$doc)\"" >> ${DocHeaderFile}
done